name: onelab_experiments
description: This page is intended for demonstrating and testing experimental Pansy UI widgets.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.11
  rest_router: ^0.1.0
  video_player: ^0.10.11+2
  http: ^0.12.1
  transparent_image: ^1.0.0

  # ui
  pansy_ui:
    git: git://github.com/oneLab-Projects/pansy_ui.git
  flutter_brand_icons: ^1.1.0
  material_design_icons_flutter: ^4.0.5345
  percent_indicator: ^2.1.5

flutter:
  uses-material-design: true
