name: onelab_experiments
description: This page is intended for demonstrating and testing experimental Pansy UI widgets.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^5.4.11

  #ui
  pansy_ui:
    git: git://github.com/oneLab-Projects/pansy_ui.git
  flutter_brand_icons: ^1.1.0
  material_design_icons_flutter: ^4.0.5345

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
